spring:
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:8080/api
      username: root
      password: root
   h2:
      console:
         enabled: true
         path: /h2
   jpa:
      hibernate:
         ddl-auto: update
         show-sql: true

server:
   port: 8080

